### PR TITLE
N9H30 can use the NUC970 kernel

### PR DESCRIPTION
**Pull request by parrotgeek1**

### CODE REVIEW

**Review by yachen — COMMENTED** [review]
N32905 tool cannot support 01/03, 926, n9h26.

**Comment by parrotgeek1** [comment]
Sorry. I didn't know this because there are some files with names FA92 And FA95. I'll edit it

**Comment by parrotgeek1** [comment]
Fixed it

**Comment by yachen** [comment]
Merged, thanks.

**Pull request merged**
